### ISSUE TITLE
The "android" command is deprecated.

### ISSUE THREAD

**Issue by amadeu01** [joshrlesch/fastlane-plugin-instrumented_tests#12]
## Problem 

https://github.com/joshrlesch/fastlane-plugin-instrumented_tests/blob/3d1fea24af814db3d15d045268c6afe7aef540fd/lib/fastlane/plugin/instrumented_tests/actions/instrumented_tests_action.rb#L45

Here, you use `android` from android tools. But, it is deprecated right now. 

>
> This tool is no longer supported. Instead use Android Studio to create AVDs and create projects, or use sdkmanager to view and install SDK packages from the command line.
>

## Links that might be helpful 

-  [Question Stackoverflow](https://stackoverflow.com/questions/50016303/the-android-command-is-deprecated)
- [Documentation Android](https://developer.android.com/studio/run/emulator-commandline)
- [Tools help android](https://developer.android.com/studio/tools/help/android)

**Comment by joshrlesch** [comment]
yup, I have a PR open to update this. https://github.com/joshrlesch/fastlane-plugin-instrumented_tests/pull/9

I'll try to get this updated soon

**Comment by joshrlesch** [comment]
released update to rubygems
