### ISSUE TITLE
Create avd and start command not working properly

### ISSUE THREAD

**Issue by gerits** [joshrlesch/fastlane-plugin-instrumented_tests#2]
Hello

I tried to run my test with this plugin, but had some issues.
### create emulator

 When creating the emulator a question is asked if you want to create a hardware profile for this emulator. To skip this question I found no automated solution so I had to inject "no" into the command. This question was however hidden so it just acted as if it was still doing something.
### start emulator

When starting the virtual device it often did not start properly, no output was written to the log file but it did not continue. I changed the way the output was written and then it worked properly. Another issues I had is that the option -no-audio was not recognized. 
### issue handling

Another issue I had is that with all the above issues the error was written somewhere in a log, but the plugin was not aware that anything went wrong. But I did not find a solution on how to handle errors properly in this case.

Not sure if this is related to the version of the emulator/sdk or a general issue. (android-sdk-version: **25.1.7**)

These are the changes I made to get things working, if these are common problems I'll create a pull request:

```
diff --git a/lib/fastlane/plugin/instrumented_tests/actions/instrumented_tests_action.rb b/lib/fastlane/plugin/instrumented_tests/actions/instrumented_tests_action.rb
index 27ac89c..1b425bf 100644
--- a/lib/fastlane/plugin/instrumented_tests/actions/instrumented_tests_action.rb
+++ b/lib/fastlane/plugin/instrumented_tests/actions/instrumented_tests_action.rb
@@ -54,7 +54,7 @@ module Fastlane
         avd_options = params[:avd_options] unless params[:avd_options].nil?
         avd_abi = "--abi #{params[:avd_abi]}" unless params[:avd_abi].nil?
         avd_tag = "--tag #{params[:avd_tag]}" unless params[:avd_tag].nil?
-        create_avd = ["#{params[:sdk_path]}/tools/android", "create avd", avd_name, target_id, avd_abi, avd_tag, avd_options].join(" ")
+        create_avd = ["echo 'no' |", "#{params[:sdk_path]}/tools/android", "create avd", avd_name, target_id, avd_abi, avd_tag, avd_options].join(" ")

         UI.important("Creating AVD...")
         Action.sh(create_avd)
@@ -63,8 +63,8 @@ module Fastlane
       def self.start_emulator(params)
         UI.important("Starting AVD...")
         ui_args="-gpu on"
-        ui_args="-no-audio -no-window" if params[:avd_hide]
-        start_avd = ["#{params[:sdk_path]}/tools/emulator", "-avd #{params[:avd_name]}", "#{ui_args}", "-port #{params[:avd_port]} &>#{@emulator_output.path} &"]
+        ui_args="-no-window" if params[:avd_hide]
+        start_avd = ["#{params[:sdk_path]}/tools/emulator", "-avd #{params[:avd_name]}", "#{ui_args}", "-port #{params[:avd_port]} >#{@emulator_output.path} 2>&1 &"]
         Action.sh(start_avd)
       end
```

**Comment by lexxdark** [comment]
Hello, thank you for the feedback. :)

There is no proper error handling when starting the emulator unfortunatley, at least I haven't found a solution anywhere. The best "error-handling" I've seen to date is to add a timeout for waiting the emulator to boot. Probably our best solution of error handling is to spit out the log (with the error output as well) if we get to the timeout.

About the echo "no" I'm a bit afraid. I will be able to work on this probalby this weekend.

**Comment by lexxdark** [comment]
This should be fixed. I've added more complete error handling. Also when there are errors the emulator output is printed.

I have removed the "-no-audio" parameter and also allowed overriding the parameter via avd_emulator_options parameter (also available in env variable flavor)

I have some doubts on what happens if the emulator outputs a lot of data, but aside this worked great on all encountered errors that I had.

Please reopen if you your issues aren't fixed
